[package]
name = "cato"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cairo_execute = "2.14.0"

[dev-dependencies]
snforge_std = "0.38.0"

[executable]

[cairo]
enable-gas = false

[scripts]
test = "snforge test"
