[package]
name = "cato"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cairo_execute = "2.14.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.38.0" }

[[target.executable]]
name = "prove_cat"
sierra = true
enable-gas = false

[scripts]
test = "snforge test"
